### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by kentcdodds** [TheLarkInn/ama#1]
For example: https://github.com/kentcdodds/ama/issues/5

> Screenshot please. It tells a lot about a person.

**Comment by TheLarkInn** [comment]
![image](https://cloud.githubusercontent.com/assets/3408176/18595842/7a7c5f36-7c14-11e6-8c67-2387fcfdd6cc.png)

@kentcdodds That face on your little dude is priceless.
